# Autogenerated wrapper script for pdfcpu_jll for i686-w64-mingw32
export pdfcpu

JLLWrappers.@generate_wrapper_header("pdfcpu")
JLLWrappers.@declare_executable_product(pdfcpu)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        pdfcpu,
        "bin\\pdfcpu.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
