# Autogenerated wrapper script for pdfcpu_jll for powerpc64le-linux-gnu
export pdfcpu

JLLWrappers.@generate_wrapper_header("pdfcpu")
JLLWrappers.@declare_executable_product(pdfcpu)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        pdfcpu,
        "bin/pdfcpu",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
